name: Deploy docker image and update production

on:
    push:
        branches:
            - 'main'

env:
    REGISTRY: ghcr.io
    DEPLOY_USER: deploy
    HOST: ${{ vars.VPS_IP }} 
    DOCKER_STACK_NAME: velonuxt 
    IMAGE_NAME: vovastelmashchuk/velonuxt
    BASE_URL: ${{ vars.BASE_URL }}
    MONGO_URI: ${{ secrets.MONGO_URI }}
    JWT_SECRET: ${{ secrets.JWT_SECRET }}
    GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}
    DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: |
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
                  build-args: |
                      GIT_COMMIT_SHA=${{ github.sha }}

    deploy:
        runs-on: ubuntu-latest
        needs:
            - build-and-push-image
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Create .env file for Docker Stack
              run: |
                  echo "IMAGE_NAME='${{ env.IMAGE_NAME }}'" >> .env
                  echo "GIT_COMMIT_HASH='${{ github.sha }}'" >> .env
                  echo "BASE_URL='${{ env.BASE_URL }}'" >> .env
                  echo "MONGO_URI='${{ env.MONGO_URI }}'" >> .env
                  echo "JWT_SECRET='${{ env.JWT_SECRET }}'" >> .env
                  echo "GOOGLE_CLIENT_ID='${{ env.GOOGLE_CLIENT_ID }}'" >> .env

            - name: Setup docker remote context
              uses: cssnr/stack-deploy-action@v1
              with:
                  name: ${{ env.DOCKER_STACK_NAME }}
                  file: docker-stack.yml
                  host: ${{ env.HOST }}
                  port: 22
                  user: ${{ env.DEPLOY_USER }}
                  ssh_key: ${{ env.DEPLOY_SSH_PRIVATE_KEY }}
                  env_file: .env
                  detach: false
                  prune: true
                  resolve_image: 'always'
                  summary: true